name: C++ Tests
on: 
    push:  
    pull_request:

jobs:
    build-on-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake build-essential ninja-build g++
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release
            - name: Build Project
              run: |
                cmake --build out
    build-on-windows:
        runs-on: windows-latest
        steps:
            - name: Install dependencies
              run: |
                choco install cmake ninja
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release
            - name: Build project
              run: |
                cmake --build out
    build-on-linux-dynamiclib:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake build-essential ninja-build g++
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPILE_AS_SHARED_LIBRARY=ON
            - name: Build Project
              run: |
                cmake --build out
    build-on-windows-dynamiclib:
        runs-on: windows-latest
        steps:
            - name: Install dependencies
              run: |
                choco install cmake ninja
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPILE_AS_SHARED_LIBRARY=ON
            - name: Build project
              run: |
                cmake --build out