name: C++ Tests
on: 
    push:  
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake build-essential ninja-build g++
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release
            - name: Build Project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Linux, Static lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    build-on-windows:
        runs-on: windows-latest
        steps:
            - name: Install dependencies
              run: |
                choco install cmake ninja
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release
            - name: Build project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Windows, Static lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    build-dynamiclib:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake build-essential ninja-build g++
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPILE_AS_SHARED_LIBRARY=ON
            - name: Build Project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Linux, Dynamic lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    build-on-windows-dynamiclib:
        runs-on: windows-latest
        steps:
            - name: Install dependencies
              run: |
                choco install cmake ninja
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPILE_AS_SHARED_LIBRARY=ON
            - name: Build project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Windows, Dynamic lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    publish-headers:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: Terminate includes (Cross-platform, Dynamic lib OR Static lib)
                path: |
                  include/terminate/*
    package-runtime-files-as-deb:
        runs-on: ubuntu-latest
        needs: build-dynamiclib
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                path: repo
            - name: Create directories
              run: |
                mkdir -p temp/DEBIAN temp/usr/lib/x86_64-linux-gnu
            - name: Download binaries
              uses: actions/download-artifact@v4
              with:
                name: Terminate binaries (Linux, Dynamic lib)
                path: terminate-bin
            - name: Move files into correct locations
              run: |
                mv terminate-bin/libterminate.so temp/usr/lib/x86_64-linux-gnu/libterminate.so.0.0.0
                mv repo/debian_package/runtime-package-info.txt temp/DEBIAN/control
                cd temp/usr/lib/x86_64-linux-gnu
                ln -s libterminate.so.0.0.0 libterminate.so.0
                cd ../../../../
            - name: Build debian package
              run:
                dpkg-deb --build temp libterminate-runtime.deb
            - name: Upload debian package as artifact
              uses: actions/upload-artifact@v4
              with:
                path: libterminate-runtime.deb
                name: Terminate Debian package (Debian only, Dynamic lib)
            - name: Output folder structure
              run: |
                tree .
                