name: C++ Tests
on: 
    push:  
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake build-essential ninja-build g++
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release
            - name: Build Project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Linux, Static lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    build-on-windows:
        runs-on: windows-latest
        steps:
            - name: Install dependencies
              run: |
                choco install cmake ninja
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release
            - name: Build project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Windows, Static lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    build-dynamiclib:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake build-essential ninja-build g++
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPILE_AS_SHARED_LIBRARY=ON
            - name: Build Project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Linux, Dynamic lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    build-on-windows-dynamiclib:
        runs-on: windows-latest
        steps:
            - name: Install dependencies
              run: |
                choco install cmake ninja
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Generate build files with CMake
              run: |
                cmake -S . -B out -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPILE_AS_SHARED_LIBRARY=ON
            - name: Build project
              run: |
                cmake --build out
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Terminate binaries (Windows, Dynamic lib)
                path: |
                  out/*.a
                  out/*.dll
                  out/*.so
                  out/*.lib
    publish-headers:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: Terminate includes (Cross-platform, Dynamic lib OR Static lib)
                path: |
                  include/terminate/*
              